{
 "title": "ARISTA Switch  Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": {
     "query": "label_values({source=~\"172.22.1.250|172.22.0.5\"},source)"
    }
   },
   { "name": "Ethernet", "query": { "query": "label_values(interface_name)" } }
  ]
 },
 "panels": [
  { "title": "BASED ON PORTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bit Rate (Octets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_in_octets{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_out_octets{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Broadcast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_in_broadcast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_out_broadcast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_in_multicast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_out_multicast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_in_unicast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(interface_name) (rate(interfaces_counters_out_unicast_pkts{source=\"$source\", interface_name=\"$Ethernet\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  { "title": "BASED ON SWITCHES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bit Rate (Octets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(source) (rate(interfaces_counters_in_octets{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(source) (rate(interfaces_counters_out_octets{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(source) (rate(interfaces_counters_in_multicast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(source) (rate(interfaces_counters_out_multicast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Unicast Packets ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(source) (rate(interfaces_counters_in_unicast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(source) (rate(interfaces_counters_out_unicast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "Broadcast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by(source) (rate(interfaces_counters_in_broadcast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}}  (IN)"
    },
    {
     "expr": "avg by(source) (rate(interfaces_counters_out_broadcast_pkts{source=\"$source\"}[1m]))",
     "legendFormat": "{{interface_name}} (OUT)"
    }
   ]
  },
  {
   "title": "SYSTEM MERICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU util ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 1, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "CPU_util ", "legendFormat": "{{source}}" }
     ]
    },
    {
     "title": "Mem Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "RAM_memFree", "legendFormat": "{{source}}" }
     ]
    },
    {
     "title": "Mem Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "RAM_memAvailable", "legendFormat": "{{source}}" }
     ]
    }
   ]
  }
 ]
}