{
 "title": "SYSTEM METRICS",
 "time": { "from": "2024-08-05T02:54:11.028Z", "to": "2024-08-05T02:56:46.081Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(cpu_usage_irq,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU  user",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "irate(cpu_usage_user{host=\"$host\"}[5m])",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "cpu_usage_idle{host=\"$host\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "CPU system",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "irate(cpu_usage_irq{host=\"$host\"}[5m]) + irate(cpu_usage_softirq{host=\"$host\"}[5m]) + irate(cpu_usage_system{host=\"$host\"}[5m])",
       "legendFormat": "{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk  Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free{host=\"$host\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_used{host=\"$host\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(host) (disk_total{host=\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "temp_temp{host=\"$host\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_total{host=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_free{host=\"$host\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_total{host=\"$host\"} - mem_buffered{host=\"$host\"} - mem_cached{host=\"$host\"} - mem_slab{host=\"$host\"} - mem_free{host=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "expr": "system_load1", "legendFormat": "{{host}}" },
      { "expr": "system_load15", "legendFormat": "{{host}}" },
      { "expr": "system_load5", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "System Uptime ",
     "type": "gauge",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "clockms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_uptime_total", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "System CPUs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_n_cpus", "legendFormat": "{{host}}" }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "kernel total interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(kernel_interrupts_total{host=\"$host\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kernel total processes forked",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(kernel_processes_forked_total{host=\"$host\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}