{
 "title": "SYSTEM STATUS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "DPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BF2/172.22.3.2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"bf2\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AMD/172.22.3.1",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"amd\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MARVEL/172.22.3.3",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"mrv\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MEV/192.168.0.2 ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_Virtual_Temperature_Sensor_C{host=\"a95b43743cce\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "SWITCHES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "A100G /172.22.1.250",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(CPU_idle{source=\"172.22.1.250\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ToR/172.22.0.5",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(CPU_idle{source=\"172.22.0.5\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "DPU HOST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "DH1/172.22.1.1",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"dh1\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DH2/172.22.1.2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"bf2\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DH3/172.22.1.3",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"dh3\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DH4/172.22.1.4",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"dh4\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DH9/172.22.1.9",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"dh9\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "SERVERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Management/172.22.0.1",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"mgmt\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "tgen/172.22.1.100",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent_over_time(temp_temp{host=\"tgen1\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}