# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---

- name:
  hosts: hostbmcs
  become: yes
  tasks:
    - name: Get Firmware Inventory
      community.general.redfish_info:
        category: Update
        command: GetFirmwareInventory
        baseuri: "{{ ansible_host }}"
        username: "{{ ansible_user | default(ansible_env.USER) }}"
        password: "{{ ansible_password }}"
      register: result

    - name: Debug print first firmware entry version
      ansible.builtin.debug: var=result.redfish_facts.firmware.entries[0].Version

    - name: Get BIOS attributes
      community.general.redfish_info:
        category: Systems
        command: GetBiosAttributes
        baseuri: "{{ ansible_host }}"
        username: "{{ ansible_user | default(ansible_env.USER) }}"
        password: "{{ ansible_password }}"
      register: result
      tags: ["TEST"]

    - name: Debug print bios serial number
      ansible.builtin.debug: msg={{ result.redfish_facts.bios_attribute.entries[0][1].SerialNumber | default(result.redfish_facts.bios_attribute.entries[0][1].SystemServiceTag) }}


    - name: Debug print bios serial number
      when: inventory_hostname == 'dh1bmc'
      ansible.builtin.debug: msg={{ result.redfish_facts.bios_attribute.entries[0][1].AcPwrRcvryUserDelay | default(result.redfish_facts.bios_attribute.entries[0][1].SystemServiceTag) }}
      tags: ["TEST"]

        # TODO: configre BIOS to be always on ( see lab/hardware/dh123) and any virtualization or hyper threading settings we might need

    # Updating Bios attributes in host BMCs
    - name: Set BIOS attributes
      community.general.redfish_config:
       category: Systems
       resource_id: "{{ resource_id }}"
       command: SetBiosAttributes
       bios_attributes: "{{ bios_attributes }}"
       baseuri: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
      register: bios_attribute

    # DELL ONLY: Updating BIOS settings requires creating a configuration job
    # to schedule the BIOS update, so comment out below for non-Dell systems.

    - name: Create BIOS configuration job (schedule BIOS setting update)
      when: inventory_hostname == 'dh1bmc'
      community.general.idrac_redfish_command:
       category: Systems
       command: CreateBiosConfigJob
       baseuri: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
      when: bios_attribute.changed
      register: bios_config_job

    - name: Reboot system to apply new BIOS settings
      when: inventory_hostname == 'dh1bmc'
      community.general.redfish_command:
       category: Systems
       command: PowerReboot
       resource_id: "{{ resource_id }}"
       baseuri: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
      when: bios_config_job.changed
