# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---

- name:
  hosts: hostbmcs
  become: yes
  vars:
    iLO_bios_attributes_AutoPowerOn:
      "AutoPowerOn": "AlwaysPowerOn"
    iDRAC_bios_attributes_AcPwr:
       "AcPwrRcvry": "On"
       "AcPwrRcvryDelay": "Immediate"
       "AcPwrRcvryUserDelay": 10
  tasks:
    - name: Get Firmware Inventory
      community.general.redfish_info:
        category: Update
        command: GetFirmwareInventory
        baseuri: "{{ ansible_host }}"
        username: "{{ ansible_user | default(ansible_env.USER) }}"
        password: "{{ ansible_password }}"
      register: result

    - name: Debug print first firmware entry version
      ansible.builtin.debug: var=result.redfish_facts.firmware.entries[0].Version

    - name: Get BIOS attributes
      community.general.redfish_info:
        category: Systems
        command: GetBiosAttributes
        baseuri: "{{ ansible_host }}"
        username: "{{ ansible_user | default(ansible_env.USER) }}"
        password: "{{ ansible_password }}"
      register: result

    - name: Debug print bios serial number
      ansible.builtin.debug: msg={{ result.redfish_facts.bios_attribute.entries[0][1].SerialNumber | default(result.redfish_facts.bios_attribute.entries[0][1].SystemServiceTag) }}

    # TODO: configre BIOS to be always on ( see lab/hardware/dh123) and any virtualization or hyper threading settings we might need

    # Bios attributes update for 'Auto power on'
    # TODO: Add dh1bmc and dh3bmc when ready or automate based on BMC type
    - name: Set BIOS attributes iLO
      when: inventory_hostname == 'dh2bmc'
      community.general.redfish_config:
       category: Systems
       command: SetBiosAttributes
       bios_attributes: "{{ iLO_bios_attributes_AutoPowerOn }}"
       baseuri: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
      register: bios_attribute
      tags: ["TEST"]

    - name: Set BIOS attributes iDRAC
      when: inventory_hostname == 'dh4bmc'
      community.general.redfish_config:
       category: Systems
       command: SetBiosAttributes
       bios_attributes: "{{ iDRAC_bios_attributes_AcPwr }}"
       baseuri: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
      register: bios_attribute
      tags: ["TEST"]

    # DELL ONLY: Updating BIOS settings requires creating a configuration job
    # to schedule the BIOS update, so comment out below for non-Dell systems.

#    - name: Create BIOS configuration job (schedule BIOS setting update)
#      community.general.idrac_redfish_command:
#       category: Systems
#       command: CreateBiosConfigJob
#       baseuri: "{{ ansible_host }}"
#       username: "{{ ansible_user }}"
#       password: "{{ ansible_password }}"
#      when: bios_attribute.changed

#    - name: Reboot system to apply new BIOS settings
#      community.general.redfish_command:
#       category: Systems
#       command: PowerReboot
#       baseuri: "{{ ansible_host }}"
#       username: "{{ ansible_user }}"
#       password: "{{ ansible_password }}"
#      when: bios_attribute.changed
